version: 2.1
orbs:
  jira: circleci/jira@1.3.0
  aws-cli: circleci/aws-cli@1.3.2
jobs:
  deploy:
  
workflows:
  build_and_deploy:
    jobs:
      - deploy:
          name: deploy-staging
          context:
            - staging
          post-steps:
            - jira/notify
          filters:
            branches:
              only: master
      - block_production:
          type: approval
          requires:
            - deploy-staging
      - deploy:
          name: deploy-production
          context:
            - prod
          post-steps:
            - jira/notify
          filters:
            branches:
              only: master
          requires:
            - block_production